version: '3.8'
services:
  dynamodb-local:
    image: "zestyco/dynamodb-challenge:amd"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
